### ISSUE TITLE
Can't connect to my server

### ISSUE THREAD

**Issue by hadim** [jrgp/thdgameserveradmin#1]
The error message is the following : 

```
clicked connect
passed checks
in background
Connecting to 90.249.34.212:50301 with *****
Sending keepalive to see if writing fails which means we're disconnected
Disconnecting
```

Note that ingame rcon login is working perfectly. And I also set `sv_tcpr = 1` in my config.

PS: Ip and password are incorrect

**Comment by jrgp** [comment]
What OS + java version? Are you able to connect with telnet?

**Comment by hadim** [comment]
Sorry for the noise, it works now... (network issue I guess)

**Comment by jrgp** [comment]
Glad to hear it. Would definitely appreciate comments / suggestions / feature requests. :)
